# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "inhmt"
    assignees:
      - "inhmt"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      # Next.js関連の依存関係をまとめて更新
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react*"
          - "eslint-config-next"
      # Prisma関連の依存関係をまとめて更新
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      # 開発用ツールをまとめて更新
      dev-tools:
        patterns:
          - "eslint*"
          - "prettier"
          - "@eslint/*"
          - "typescript"
          - "tsx"
      # UI関連の依存関係をまとめて更新
      ui-tools:
        patterns:
          - "tailwindcss*"
          - "daisyui"
          - "@tailwindcss/*"
          - "react-icons"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "inhmt"
    assignees:
      - "inhmt"
    commit-message:
      prefix: "ci"
      include: "scope"